language: bash

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
before_install:
  - sudo apt update --yes
install:
  - npm install -g bats
script:
  - make lint
  - make test
