<<<<<<< HEAD
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
# install: "pip install -r requirements.txt"
# # command to run tests
# script: nosetests
=======
language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
install:
  - sudo apt-get install -qq bc
script:
  - bats ./test.bats
>>>>>>> samurai-next
