language: node_js
dist: trusty
before_script:
  - apt-get update && apt-get upgrade -y
  - $SHELL --version 2> /dev/null || dpkg -s $SHELL 2> /dev/null || which $SHELL
  - curl --version
  - shellcheck --version
  - command -v nvm
  - nvm install node
  - nvm use node
  - npm install -g bats
script:
  - make lint
  - make test
