language: bash

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
before_script:
  - yarn global add bats
script:
  - make lint
  - make test
