language: bash
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt update --yes
install:
  - sudo apt install bats --yes
script:
  - bats test.bats
