language: node_js
dist: xenial
before_script:
  - $SHELL --version 2> /dev/null || dpkg -s $SHELL 2> /dev/null || which $SHELL
  - curl --version
  - shellcheck --version
  - command -V nvm
  - nvm install node
  - nvm use node
  - npm install -g bats
script:
  - make build
  - make test
